package br.thiago.teste.contrato.entity;

import com.amazonaws.services.dynamodbv2.datamodeling.*;
import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.NoArgsConstructor;
import org.hibernate.validator.constraints.br.CPF;

import javax.validation.constraints.NotBlank;

@Data
@NoArgsConstructor
@AllArgsConstructor
@Builder
@DynamoDBTable(tableName = "contract")
public class Contract {

    @DynamoDBAutoGeneratedKey
    @DynamoDBHashKey(attributeName = "id")
    @NotBlank
    private String idContract;

    @NotBlank
    @DynamoDBAttribute (attributeName = "cpf")
    private String cpf;

    @NotBlank
    @DynamoDBAttribute (attributeName = "product")
    private String product;

}
